version: '3.7'

services:
    db_transferencias:
        image: postgres:12.0-alpine
        container_name: db_transferencias
        volumes: 
            - postgres_data_transferencias:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        env_file: 
            - ./.env
    pgadmin_transferencias:
        image: dpage/pgadmin4
        container_name: pgadmin_transferencias
        environment: 
            - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - pgadmin4:/var/lib/pgadmin
        ports: 
            - 8080:80
        logging:
            driver: none  
volumes: 
    postgres_data_transferencias:
    pgadmin4: