# Generated by Django 3.2 on 2022-09-16 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('0', 'PENDIENTE'), ('1', 'CONFIRMADO'), ('2', 'RECHAZADO')], default=0, max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
