# Generated by Django 3.2 on 2022-09-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0003_transaccion_cuenta_bancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_destino', models.IntegerField(verbose_name='Cuenta Destino')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('estado', models.CharField(choices=[('0', 'PENDIENTE'), ('1', 'CONFIRMADO'), ('2', 'RECHAZADO')], default=0, max_length=1, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferencias.cuentabancaria')),
                ('entidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferencias.entidad')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferencias.moneda')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
