# Generated by Django 3.2 on 2022-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0004_auto_20220916_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='cuenta_origen',
            new_name='nro_cuenta',
        ),
    ]
