# Generated by Django 3.2 on 2022-09-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0005_rename_cuenta_origen_transferencia_nro_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='nro_cuenta',
            new_name='cuenta_origen',
        ),
    ]
