# Generated by Django 3.2 on 2022-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0006_rename_nro_cuenta_transferencia_cuenta_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('PEN', 'PENDIENTE'), ('CON', 'CONFIRMADO'), ('REC', 'RECHAZADO')], default=0, max_length=3, verbose_name='Estado'),
        ),
    ]
