# Generated by Django 3.2 on 2022-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0007_alter_transferencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='estado',
            field=models.CharField(choices=[('PEN', 'PENDIENTE'), ('CON', 'CONFIRMADO'), ('REC', 'RECHAZADO')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='monto',
            field=models.FloatField(verbose_name='Monto'),
        ),
    ]
